# File: .streamlit/config.toml

[theme]

backgroundColor = "#f0f2f6"  # (Ví dụ: màu xám nhạt)

secondaryBackgroundColor = "#e0e4eb" # (Ví dụ: màu xám đậm hơn)

textColor = "#070707ff"


font = "sans serif"